name: Build PHP Images for arm64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest-arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and archive PHP images for arm64
        run: |
          mkdir -p build/images
          mkdir -p build/logs
          ./build/build_arm64.sh

      - name: Upload PHP images archive for arm64
        uses: actions/upload-artifact@v4
        with:
          name: php_images_arm64
          path: build/images/php_images.tar.gz
          retention-days: 7